AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Patient Service API - sample-service::sample-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  PatientServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ps.api.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/sample-service-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PatientServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: PatientServiceApi
